[workspace]
members = [ "common", "trie_diff", "trie_query"]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
clap = { version = "4.4.6", features = ["derive", "env"] }
eth_trie_utils = "0.6.0"
protocol_decoder = { git = "https://github.com/0xPolygonZero/proof-protocol-decoder.git", rev = "e0e9338366afe687f22ba0ab9532eb28f326f4b4" }
serde_json = "1.0.111"

[patch."https://github.com/0xPolygonZero/proof-protocol-decoder.git"]
protocol_decoder = { path = "../../proof_protocol_decoder/protocol_decoder" }

[patch.crates-io]
eth_trie_utils = { path = "../../eth_trie_utils" }

[patch."https://github.com/0xPolygonZero/eth_trie_utils.git"]
eth_trie_utils = { path = "../../eth_trie_utils" }
