[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpt_trie = { workspace = true }
hex = "0.4.3"

trace_decoder = { workspace = true }
serde_json = { workspace = true }
